# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="powerlevel10k/powerlevel10k"

plugins=(git aws vi-mode zoxide)

source $ZSH/oh-my-zsh.sh


alias vim="nvim"
alias k="kubectl"
alias dcp="docker-compose"
export EDITOR="nvim"
export KUBE_CONFIG_PATH="~/.kube/config"
eval "$(uv generate-shell-completion zsh)"
export PATH="$PATH:$HOME:.cargo/bin:$HOME/.luaenv/bin:$HOME/.local/bin::$HOME/go/bin"
export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
